# Generated by Django 5.1 on 2024-08-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_name_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
